### ISSUE TITLE
JSChess

### ISSUE THREAD

**Issue by Darlanio** [Darlanio/Darlanio-ChessDatabase#1]
Plan to create a webpage with Chessboard and an AI in Javascript to play against. Realizing this will be for beginner level only since I am just a beginner at JavaScript and only an intermediate chessplayer myself.

**Comment by Darlanio** [comment]
Still a lot bugs to squash but it seems to work just fine. I have added an openingbook which works fine and gives more random games. The script handles both castling and en passant, but some bugs seems to be related to these features. Due to horizon effect the script plays faster and a lot worse in endgames. I estimate chessplaying strength to less than ELO 1200.

**Comment by Darlanio** [comment]
Realized this is in the wrong project (MyChessDatabase Project instead of JSChess Project). Closing this issue.

**Comment by ppchucho** [comment]
MyChessDatabase Project instead of JSChess Project). Closing this issue

**Comment by Darlanio** [comment]
Nice of you to drop by. Sadly I have had no time to work on this project for some time now...
